---
kind: pipeline
name: deploy to swarm-test.autonomic.zone
steps:
  - name: deployment
    image: decentral1se/stack-ssh-deploy:latest
    settings:
      host: swarm-test.autonomic.zone
      stack: traefik
      deploy_key:
        from_secret: drone_ssh_swarm_test
    environment:
      DOMAIN: traefik.swarm-test.autonomic.zone
      STACK_NAME: traefik
      LETS_ENCRYPT_ENV: production
      LETS_ENCRYPT_EMAIL: helo@autonomic.zone
      TRAEFIK_YML_VERSION: v3
      FILE_PROVIDER_YML_VERSION: v2
trigger:
  branch:
    - master
---
kind: pipeline
name: recipe release
steps:
  - name: release a new version
    image: decentral1se/drone-abra:latest
    settings:
      command: recipe traefik release
      deploy_key:
        from_secret: abra_bot_deploy_key
