---
version: "3.8"

services:
  app:
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 2222
        published: 2222
        mode: host
